### ISSUE TITLE
Extension name?

### ISSUE THREAD

**Issue by oovm** [badicsalex/peginator#14]
Can you open the `discussion`, I have some non-issue questions to ask.

I am going to write a highlighting and formatting plugin, and I need to bind a extension, what do you think is suitable?

**Comment by badicsalex** [comment]
I'm using .ebnf in all my projects, because the current syntax is inspired by that, and currently existing highlighters work good enough if you call the files ebnf.

BTW, this is the VIM syntax plugin I use: https://github.com/badicsalex/dotfiles/blob/master/nvim/syntax/ebnf.vim
It is a forked version of Tatsu's syntax files: https://github.com/neogeny/TatSu/tree/master/etc

**Comment by oovm** [comment]
no no no, not label, i mean this thing

![image](https://user-images.githubusercontent.com/17541209/204073420-a23dd4c9-5589-4c2b-bee3-393a98352a0f.png)

**Comment by badicsalex** [comment]
Oh, I see, sorry.

I enabled discussions :)
