### ISSUE TITLE
Support stack match

### ISSUE THREAD

**Issue by oovm** [badicsalex/peginator#2]
In some languages, something like [pest/stack](https://pest.rs/book/grammars/syntax.html#the-stack-wip) is required.

Used for things like string matching.

If the left side eats `r#"`, then the right side needs to match `"#`.

If the left side eats `r##"`, then the right side needs to match `"##`.

More `#` and so on.

**Comment by badicsalex** [comment]
If done like in pest, that functionality would completely clash with memoization, since at that point the memoization cache key is not just the position and the rule name, but the contents of this stack too. (this is not a problem if the stack is per-rule and not "global" like in pest)

I think this use-case is rare-enough (I can only think of rust raw string strings and bash heredocs) that in this case you should just write a function named `parse_Whatever`, where `Whatever` will then be a virtual rule that behaves just like the "regular" rules, which have generated parse functions. This is how the `char` "field type" is [actually implemented.](https://github.com/badicsalex/peginator/blob/master/src/runtime/builtin_parsers.rs#L11)

Is this an important functionality for you? Are you trying to parse an existing language, or something custom designed?

**Comment by badicsalex** [comment]
Closing as "won't do" for now, as I think all cases can be solved with relatively simple external parsers.
